# Generated by Django 6.0.7 on 2026-07-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('maxima', models.IntegerField(choices=[(20, 'MAXIMA 20'), (30, 'MAXIMA 30'), (60, 'MAXIMA 60')], default=20)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['maxima', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MatiereClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='classes.classe')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_enseignees', to='teachers.teacher')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='subjects.matiere')),
            ],
            options={
                'verbose_name': 'Affectation matière-classe',
                'ordering': ['matiere__maxima', 'matiere__nom'],
                'unique_together': {('matiere', 'classe')},
            },
        ),
    ]
