# Generated by Django 6.0.7 on 2026-07-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maxima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Maxima',
                'verbose_name_plural': 'Maxima',
                'ordering': ['valeur'],
            },
        ),
        migrations.AlterField(
            model_name='matiere',
            name='maxima',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
