# Generated by Django 6.0.7 on 2026-07-19 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0002_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Utilisé pour la promotion automatique. Ordre croissant = niveaux successifs.', verbose_name='Ordre de promotion')),
                ('cycle', models.CharField(blank=True, help_text='Optionnel: Primaire, Secondaire, etc.', max_length=50, verbose_name='Cycle')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['niveau__ordre', 'nom', 'section__nom'], 'verbose_name': 'Classe'},
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='cloturee',
            field=models.BooleanField(default=False, verbose_name='Clôturée'),
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='anneescolaire',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.CreateModel(
            name='JournalOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('CREATION_ANNEE', "Création d'une année"), ('ACTIVATION_ANNEE', "Activation d'une année"), ('CLOTURE_ANNEE', "Clôture d'une année"), ('MIGRATION', 'Migration des données'), ('PROMOTION', 'Promotion des élèves'), ('ARCHIVAGE', 'Archivage')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_operations', to='classes.anneescolaire')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'opération",
                'verbose_name_plural': 'Journal des opérations',
                'ordering': ['-date_operation'],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='classes.niveau', verbose_name='Niveau'),
        ),
        migrations.CreateModel(
            name='DecisionPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('ADMIS', 'Admis — Promotion'), ('REDOUBLE', 'Redouble'), ('TRANSFERE', 'Transféré'), ('DIPLOME', 'Diplômé / Fin de cycle')], default='ADMIS', max_length=20)),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('validee', models.BooleanField(default=False, verbose_name='Validée')),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_promotion', to='classes.anneescolaire')),
                ('classe_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_arrivee', to='classes.classe', verbose_name='Classe de destination')),
                ('classe_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_depart', to='classes.classe', verbose_name="Classe d'origine")),
                ('decidee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_promotion', to='students.student')),
            ],
            options={
                'verbose_name': 'Décision de promotion',
                'verbose_name_plural': 'Décisions de promotion',
                'ordering': ['eleve__nom', 'eleve__postnom'],
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
    ]
