# Generated by Django 6.0.7 on 2026-07-20 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_phase3_niveau_cloture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaloperation',
            name='type_operation',
            field=models.CharField(choices=[('CREATION_ANNEE', "Création d'une année"), ('ACTIVATION_ANNEE', "Activation d'une année"), ('CLOTURE_ANNEE', "Clôture d'une année"), ('MIGRATION', 'Migration des données'), ('PROMOTION', 'Promotion des élèves'), ('ARCHIVAGE', 'Archivage'), ('ACTIVATION_SEMESTRE', "Activation d'un semestre"), ('PUBLICATION_SEMESTRE', "Publication d'un semestre")], max_length=30),
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, 'Premier semestre'), (2, 'Deuxième semestre')])),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIF', 'Actif'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20)),
                ('repechage_actif', models.BooleanField(default=False, verbose_name='Repêchage actif')),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('date_archivage', models.DateTimeField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='classes.anneescolaire')),
                ('publie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semestres_publies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['numero'],
                'unique_together': {('annee_scolaire', 'numero')},
            },
        ),
    ]
