# Generated by Django 6.0.7 on 2026-07-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['classe'], name='student_classe_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['nom', 'postnom'], name='student_nom_idx'),
        ),
    ]
