# Generated by Django 6.0.7 on 2026-07-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='postnom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Post-nom'),
        ),
    ]
