# Generated by Django 6.0.7 on 2026-07-16 21:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('1P', '1ère Période'), ('2P', '2ème Période'), ('EXAM1', 'Examen S1'), ('3P', '3ème Période'), ('4P', '4ème Période'), ('EXAM2', 'Examen S2'), ('REPECHAGE', 'Repêchage')], max_length=20)),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student')),
                ('matiere_classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='subjects.matiereclasse')),
            ],
            options={
                'verbose_name': 'Note',
                'unique_together': {('eleve', 'matiere_classe', 'periode')},
            },
        ),
    ]
