# Generated by Django 6.0.7 on 2026-07-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('students', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['eleve', 'periode'], name='note_eleve_periode_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['matiere_classe', 'periode'], name='note_mc_periode_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['eleve'], name='note_eleve_idx'),
        ),
    ]
