kind = "api"
previewPath = "/"
title = "SGN — Gestion scolaire"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "Django SGN"
paths = ["/"]

[services.development]
run = "cd /home/runner/workspace/school_app && uv run python3 manage.py runserver 0.0.0.0:8000 --noreload"
