# Generated by Django 6.0.7 on 2026-07-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles_bulletin', to='classes.classe')),
            ],
            options={
                'verbose_name': 'Modèle de bulletin',
                'verbose_name_plural': 'Modèles de bulletins',
                'ordering': ['-annee_scolaire__annee', 'classe__nom'],
                'unique_together': {('classe', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='ModeleBulletinMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.matiere')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='bulletin.modelebulletin')),
            ],
            options={
                'verbose_name': 'Matière du bulletin',
                'ordering': ['matiere__maxima', 'ordre'],
                'unique_together': {('modele', 'matiere')},
            },
        ),
    ]
