# Generated by Django 6.0.7 on 2026-07-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='Biographie / Note'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo_profil',
            field=models.ImageField(blank=True, help_text='Photo de profil affichée dans la barre de navigation et sur la page de profil.', null=True, upload_to='profils/', verbose_name='Photo de profil'),
        ),
    ]
