# Generated by Django 6.0.7 on 2026-07-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(choices=[('classique', 'Classique'), ('moderne', 'Moderne'), ('institutionnel', 'Institutionnel'), ('minimaliste', 'Minimaliste'), ('premium', 'Premium')], default='classique', max_length=20, verbose_name='Modèle de carte')),
                ('couleur_principale', models.CharField(default='#1e3a5f', help_text='Valeur hexadécimale, ex : #1e3a5f', max_length=7, verbose_name='Couleur principale')),
                ('couleur_secondaire', models.CharField(default='#2563eb', help_text='Valeur hexadécimale, ex : #2563eb', max_length=7, verbose_name='Couleur secondaire')),
                ('devise', models.CharField(blank=True, default='Le savoir, la discipline et le travail', max_length=200, verbose_name="Devise de l'établissement")),
                ('logo_override', models.ImageField(blank=True, help_text="Laissez vide pour utiliser le logo de l'établissement", null=True, upload_to='cartes/logos/', verbose_name='Logo spécifique aux cartes')),
                ('afficher_photo', models.BooleanField(default=True, verbose_name="Photo de l'élève")),
                ('afficher_matricule', models.BooleanField(default=True, verbose_name='Matricule')),
                ('afficher_classe', models.BooleanField(default=True, verbose_name='Classe')),
                ('afficher_annee', models.BooleanField(default=True, verbose_name='Année scolaire')),
                ('afficher_qr', models.BooleanField(default=True, verbose_name='QR Code')),
                ('afficher_ddn', models.BooleanField(default=False, verbose_name='Date de naissance')),
                ('afficher_sexe', models.BooleanField(default=False, verbose_name='Sexe')),
                ('signature_prefet', models.ImageField(blank=True, null=True, upload_to='cartes/signatures/', verbose_name='Signature du préfet')),
                ('signature_directeur', models.ImageField(blank=True, null=True, upload_to='cartes/signatures/', verbose_name='Signature du directeur')),
                ('cachet', models.ImageField(blank=True, null=True, upload_to='cartes/cachets/', verbose_name="Cachet de l'établissement")),
            ],
            options={
                'verbose_name': 'Configuration des cartes',
            },
        ),
    ]
