# Generated by Django 6.0.7 on 2026-07-20 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0003_alter_journaloperation_type_operation_semestre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('SCOLAIRE', 'Scolaire'), ('ADMIN', 'Administrative'), ('PEDAGOGIQUE', 'Pédagogique'), ('PARENT', 'Parents'), ('SYSTEME', 'Système')], default='SYSTEME', max_length=20)),
                ('priorite', models.CharField(choices=[('INFO', 'Information'), ('SUCCES', 'Succès'), ('AVERT', 'Avertissement'), ('IMPORTANT', 'Important'), ('CRITIQUE', 'Critique')], default='INFO', max_length=20)),
                ('type_notif', models.CharField(blank=True, choices=[('SEMESTRE_ACTIF', 'Semestre activé'), ('SEMESTRE_PUBLIE', 'Semestre publié'), ('SEMESTRE_ARCHIVE', 'Semestre archivé'), ('REPECHAGE_ACTIF', 'Repêchage activé'), ('REPECHAGE_INACTIF', 'Repêchage désactivé'), ('ANNEE_ACTIVEE', 'Nouvelle année scolaire'), ('ANNEE_CLOTUREE', 'Année scolaire clôturée'), ('RESULTATS_PUBLIES', 'Résultats publiés'), ('BULLETIN_DISPO', 'Bulletin disponible'), ('PROMOTION_ELEVES', 'Promotion des élèves'), ('COMPTE_CREE', 'Compte créé'), ('MDP_REINIT', 'Mot de passe réinitialisé'), ('MDP_CHANGE', 'Mot de passe modifié'), ('MATIERE_AFFECTEE', 'Matière affectée'), ('MATIERE_RETIREE', 'Matière retirée'), ('SYSTEME', 'Système')], default='SYSTEME', max_length=30)),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('annee_scolaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.anneescolaire')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_envoyees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', 'lue'], name='notif_dest_lue_idx'), models.Index(fields=['destinataire', '-date_creation'], name='notif_dest_date_idx')],
            },
        ),
    ]
