# Generated by Django 6.0.7 on 2026-07-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Institut Bungulu', max_length=200)),
                ('province', models.CharField(default='Nord-Kivu', max_length=100)),
                ('ville', models.CharField(default='Beni', max_length=100)),
                ('commune', models.CharField(default='Bungulu', max_length=100)),
                ('code', models.CharField(default='62024 / 101 / 03 / 1', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
            ],
            options={
                'verbose_name': "Informations de l'école",
            },
        ),
    ]
