# Generated by Django 6.0.7 on 2026-07-18 19:59

import django.db.models.deletion
import portail.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_portail', models.CharField(default='Portail des Résultats', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='portail/')),
                ('url_portail', models.CharField(blank=True, help_text='URL complète du portail après hébergement (ex: https://monecole.com) — utilisée pour générer les QR Codes', max_length=500)),
                ('texte_accueil', models.TextField(default='Bienvenue sur le Portail des Résultats.')),
                ('couleur_primaire', models.CharField(default='#2563EB', max_length=7)),
                ('couleur_secondaire', models.CharField(default='#1E293B', max_length=7)),
            ],
            options={
                'verbose_name': 'Configuration du portail',
            },
        ),
        migrations.CreateModel(
            name='PortailAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=portail.models.generate_token, max_length=64, unique=True)),
                ('code_acces_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('active', models.BooleanField(default=False)),
                ('date_activation', models.DateTimeField(blank=True, null=True)),
                ('tentatives_echec', models.IntegerField(default=0)),
                ('bloque_jusqu', models.DateTimeField(blank=True, null=True)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portail_acces', to='students.student')),
            ],
            options={
                'verbose_name': 'Accès portail',
                'verbose_name_plural': 'Accès portail',
            },
        ),
        migrations.CreateModel(
            name='PublicationResultats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('1P', '1ère Période'), ('2P', '2ème Période'), ('EXAM1', 'Examen S1'), ('3P', '3ème Période'), ('4P', '4ème Période'), ('EXAM2', 'Examen S2'), ('ANNUEL', 'Résultat annuel')], max_length=20)),
                ('publie', models.BooleanField(default=False)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='classes.classe')),
                ('publie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publication des résultats',
                'verbose_name_plural': 'Publications des résultats',
                'ordering': ['classe__nom', 'periode'],
                'unique_together': {('classe', 'annee_scolaire', 'periode')},
            },
        ),
    ]
